---
language: python
cache: pip
services:
  - docker
jobs:
  include:
    - python: "3.6"
      env: TOXENV=py36,flake8,pylint
    - python: "3.6-dev"
      env: TOXENV=py36,flake8,pylint
    - python: "3.7"
      env: TOXENV=py37,flake8,pylint
    - python: "3.7-dev"
      env: TOXENV=py37,flake8,pylint
    - python: "3.8"
      env: TOXENV=py38,flake8,pylint
    - python: "3.8-dev"
      env: TOXENV=py38,flake8,pylint
    - python: "3.9-dev"
      env: TOXENV=py39,flake8,pylint
    - python: "nightly"
      env: TOXENV=py3,flake8
    - python: "pypy3"
      env: TOXENV=pypy3,flake8,pylint
before_install:
  - pip install -U pip
  - pip install -U setuptools wheel
install:
  - make pip
  - pip install -U --no-use-pep517 tox flake8 pylint pytest-cov codecov
  - make docker-pull
script:
  - make flake8
  - make pylint
  - make pytest
  - make tox
after_script:
  - codecov
