---
environment:
  matrix:
    - TOXENV: py36
    - TOXENV: py37
    - TOXENV: py38
    - TOXENV: py3

build: off

install:
  - python3 -m pip install tox codecov

test_script:
  - tox

after_test:
  - codecov
