name: Transifex

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; fi

      - name: Build docs
        run: make -C docs gettext

      - name: Push
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
        run: python -m txclib.cmdline push -s
